### ISSUE TITLE
Forgot Password and Email confirmation links missing from the homepage

### ISSUE THREAD

**Issue by shachiagarwalla** [anthonyto/Zapskills#10]
Since integration of front and back end the Forgot Password and Email confirmation links have gone missing from the home page and that is the reason few RSpec tests are failing.

**Comment by anthonytokosky** [comment]
Fixed in 8f9f68e1695f789698329ddca1569087273c852b. @shachiagarwalla please verify

**Comment by shachiagarwalla** [comment]
Verified in master. closing
