### ISSUE TITLE
Must be logged in

### ISSUE THREAD

**Issue by Nordeast** [anthonyto/Zapskills#11]
I cannot access the main landing page without first being logged in.

**Comment by shachiagarwalla** [comment]
Was not that what we decided? That nothing should be accessible without logging in. Correct me if I am wrong

**Comment by Nordeast** [comment]
I believe we should be able to get to the main page, login and signup with out being logged in.

**Comment by Nordeast** [comment]
Also when you enter in zapskills.com you should be directed to the main page.

**Comment by shachiagarwalla** [comment]
But I am able to enter into login and signup pages without being logged in.

**Comment by Nordeast** [comment]
agreed. The point of the main page though is to attract users to sign up to the site. So they should be directed there first and then prompted to sign up.

**Comment by shachiagarwalla** [comment]
Yes. I agree with you. Landing page could be made accessible without logging in. Let us see what is the view point of others on this.

**Comment by Nordeast** [comment]
perfect

**Comment by anthonytokosky** [comment]
Fixed in b350f9df45da3fc3ce0ae12b2f72d768f562a49c
