### ISSUE TITLE
Entering incorrect state in search fields still yields me results

### ISSUE THREAD

**Issue by shachiagarwalla** [anthonyto/Zapskills#16]
Steps to reproduce:

Choose ruby on rails
enter city as madison
enter state as wes
enter radius as 2

There will still be a result shown for shachi (my second id)

If state is irrelevant do we need it on the search page?

**Comment by Nordeast** [comment]
similarly if you enter in characters to the radius field and numbers in the state and city field

**Comment by Nordeast** [comment]
Also should we allow for no city, state, and radius for skills that could maybe be traded virtually say over skype?

**Comment by anthonytokosky** [comment]
I've implemented a state drop down, so this is no longer an issue. The skype thing can be reopened as another issue
