### ISSUE TITLE
Entering incorrect city in search fields still yields me results

### ISSUE THREAD

**Issue by shachiagarwalla** [anthonyto/Zapskills#17]
Steps to reproduce:

Choose ruby on rails
enter city as mad
enter state as wi
enter radius as 2

There will still be a result shown for shachi (my second id)

If city is irrelevant do we need it on the search page?

**Comment by anthonytokosky** [comment]
We redesigned the search function. This should be resolved with that redesign, but we can reopen if there are further problems.
