### ISSUE TITLE
Search results/no results ambiguity

### ISSUE THREAD

**Issue by shachiagarwalla** [anthonyto/Zapskills#18]
If a skill has been taken by some user in the app and I search for something for which result is not possible I am redirected to the results page with 0 entries, whereas if a skill has not been taken by anyone in the app and I try to search the same skill, I am redirected back to the search page with the message 'no results'

Steps to reproduce:
Scenario 1:
Enter Fishing in Skills
Enter Madison in City
Enter WI in State
Enter 0.2 in Radius
Click Search- Results page with 0 entries in the table

Scenario 2:
Enter Camping in Skills
Enter Madison in City
Enter WI in State
Enter 5 in Radius
Click Search- Search page with the message "no results"

**Comment by anthonytokosky** [comment]
Resolved. If there are no results, it will always redirect to the search page and display "No results"
