### ISSUE TITLE
Experience Controller: POST Create Fails

### ISSUE THREAD

**Issue by shachiagarwalla** [anthonyto/Zapskills#22]
Presently the Post Create action in Experiences controller looks something like this:
def create
    @experience = Experience.new(experience_params)
    @experience.update_attributes(user: current_user)
    if @experience.save
      redirect_to current_user
    else
      render :new
    end
end

The update_attributes saves the record/skill for the current user and then when save is being called again duplicate skill error is thrown. 
Replacing update_attributes with assign_attributes passed the test but is this the correct way to go about it?

The test spec looks like this:
    it "experience created" do
      @user = FactoryGirl.create :user
      sign_in @user
      @skill = FactoryGirl.create :skill
      @experience = FactoryGirl.attributes_for(:experience, skill_id:@skill.id)
      post :create, { user_id:@user.id, experience: @experience}
      flash[:notice].should be_nil
      response.should_not render_template("new")
      response.should redirect_to(@user)
    end

**Comment by anthonytokosky** [comment]
Resolved.
