### ISSUE TITLE
Skills Controller: GET edit raises a template error

### ISSUE THREAD

**Issue by shachiagarwalla** [anthonyto/Zapskills#23]
On running RSpec test for GET edit
  describe "GET edit" do
    it "response is success" do
      @user = FactoryGirl.create :user
      sign_in @user
      @skill = FactoryGirl.create :skill
      get :edit, id:@skill.id
      flash[:notice].should be_nil
      response.should be_success
    end

following error is raised:
  2) SkillsController GET edit response is success
     Failure/Error: get :edit, id:@skill.id
     ActionView::MissingTemplate:
       Missing template skills/edit, application/edit with {:locale=>[:en], :formats=>[:html], :variants=>[], :handlers=>[:erb, :builder, :raw, :ruby, :coffee, :jbuilder]}. Searched in:
         \* "#RSpec::Rails::ViewRendering::EmptyTemplatePathSetDecorator:0x007fd256665a50"
     # /Users/shachiagarwalla/.rvm/gems/ruby-2.2.0@zapskills/gems/actionview-4.2.0/lib/action_view/path_set.rb:46:in `find'
     # /Users/shachiagarwalla/.rvm/gems/ruby-2.2.0@zapskills/gems/actionview-4.2.0/lib/action_view/lookup_context.rb:121:in`find'
     # /Users/shachiagarwalla/.rvm/gems/ruby-2.2.0@zapskills/gems/actionview-4.2.0/lib/action_view/renderer/abstract_renderer.rb:18:in `find_template'
     # /Users/shachiagarwalla/.rvm/gems/ruby-2.2.0@zapskills/gems/actionview-4.2.0/lib/action_view/renderer/template_renderer.rb:40:in`determine_template'
     # /Users/shachiagarwalla/.rvm/gems/ruby-2.2.0@zapskills/gems/actionview-4.2.0/lib/action_view/renderer/template_renderer.rb:8:in `render'
     # /Users/shachiagarwalla/.rvm/gems/ruby-2.2.0@zapskills/gems/actionview-4.2.0/lib/action_view/renderer/renderer.rb:42:in`render_template'
     # /Users/shachiagarwalla/.rvm/gems/ruby-2.2.0@zapskills/gems/actionview-4.2.0/lib/action_view/renderer/renderer.rb:23:in `render'
     # /Users/shachiagarwalla/.rvm/gems/ruby-2.2.0@zapskills/gems/actionview-4.2.0/lib/action_view/rendering.rb:100:in`_render_template'
     # /Users/shachiagarwalla/.rvm/gems/ruby-2.2.0@zapskills/gems/actionpack-4.2.0/lib/action_controller/metal/streaming.rb:217:in `_render_template'
     # /Users/shachiagarwalla/.rvm/gems/ruby-2.2.0@zapskills/gems/actionview-4.2.0/lib/action_view/rendering.rb:83:in`render_to_body'
     # /Users/shachiagarwalla/.rvm/gems/ruby-2.2.0@zapskills/gems/actionpack-4.2.0/lib/action_controller/metal/rendering.rb:32:in `render_to_body'
     # /Users/shachiagarwalla/.rvm/gems/ruby-2.2.0@zapskills/gems/actionpack-4.2.0/lib/action_controller/metal/renderers.rb:37:in`render_to_body'
     # /Users/shachiagarwalla/.rvm/gems/ruby-2.2.0@zapskills/gems/actionpack-4.2.0/lib/abstract_controller/rendering.rb:25:in `render'
     # /Users/shachiagarwalla/.rvm/gems/ruby-2.2.0@zapskills/gems/actionpack-4.2.0/lib/action_controller/metal/rendering.rb:16:in`render'
     # /Users/shachiagarwalla/.rvm/gems/ruby-2.2.0@zapskills/gems/actionpack-4.2.0/lib/action_controller/metal/instrumentation.rb:41:in `block (2 levels) in render'
     # /Users/shachiagarwalla/.rvm/gems/ruby-2.2.0@zapskills/gems/activesupport-4.2.0/lib/active_support/core_ext/benchmark.rb:12:in`block in ms'
     # /Users/shachiagarwalla/.rvm/gems/ruby-2.2.0@zapskills/gems/activesupport-4.2.0/lib/active_support/core_ext/benchmark.rb:12:in `ms'
     # /Users/shachiagarwalla/.rvm/gems/ruby-2.2.0@zapskills/gems/actionpack-4.2.0/lib/action_controller/metal/instrumentation.rb:41:in`block in render'
     # /Users/shachiagarwalla/.rvm/gems/ruby-2.2.0@zapskills/gems/actionpack-4.2.0/lib/action_controller/metal/instrumentation.rb:84:in `cleanup_view_runtime'
     # /Users/shachiagarwalla/.rvm/gems/ruby-2.2.0@zapskills/gems/activerecord-4.2.0/lib/active_record/railties/controller_runtime.rb:25:in`cleanup_view_runtime'
     # /Users/shachiagarwalla/.rvm/gems/ruby-2.2.0@zapskills/gems/actionpack-4.2.0/lib/action_controller/metal/instrumentation.rb:40:in `render'
     # /Users/shachiagarwalla/.rvm/gems/ruby-2.2.0@zapskills/gems/actionpack-4.2.0/lib/action_controller/metal/implicit_render.rb:10:in`default_render'
     # /Users/shachiagarwalla/.rvm/gems/ruby-2.2.0@zapskills/gems/actionpack-4.2.0/lib/action_controller/metal/implicit_render.rb:5:in `send_action'
     # /Users/shachiagarwalla/.rvm/gems/ruby-2.2.0@zapskills/gems/actionpack-4.2.0/lib/abstract_controller/base.rb:198:in`process_action'
     # /Users/shachiagarwalla/.rvm/gems/ruby-2.2.0@zapskills/gems/actionpack-4.2.0/lib/action_controller/metal/rendering.rb:10:in `process_action'
     # /Users/shachiagarwalla/.rvm/gems/ruby-2.2.0@zapskills/gems/actionpack-4.2.0/lib/abstract_controller/callbacks.rb:20:in`block in process_action'
     # /Users/shachiagarwalla/.rvm/gems/ruby-2.2.0@zapskills/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:117:in `call'
     # /Users/shachiagarwalla/.rvm/gems/ruby-2.2.0@zapskills/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:117:in`call'
     # /Users/shachiagarwalla/.rvm/gems/ruby-2.2.0@zapskills/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:151:in `block in halting_and_conditional'
     # /Users/shachiagarwalla/.rvm/gems/ruby-2.2.0@zapskills/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in`call'
     # /Users/shachiagarwalla/.rvm/gems/ruby-2.2.0@zapskills/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in `block in halting'
     # /Users/shachiagarwalla/.rvm/gems/ruby-2.2.0@zapskills/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:234:in`call'
     # /Users/shachiagarwalla/.rvm/gems/ruby-2.2.0@zapskills/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:234:in `block in halting'
     # /Users/shachiagarwalla/.rvm/gems/ruby-2.2.0@zapskills/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:234:in`call'
     # /Users/shachiagarwalla/.rvm/gems/ruby-2.2.0@zapskills/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:234:in `block in halting'
     # /Users/shachiagarwalla/.rvm/gems/ruby-2.2.0@zapskills/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in`call'
     # /Users/shachiagarwalla/.rvm/gems/ruby-2.2.0@zapskills/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in `block in halting'
     # /Users/shachiagarwalla/.rvm/gems/ruby-2.2.0@zapskills/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in`call'
     # /Users/shachiagarwalla/.rvm/gems/ruby-2.2.0@zapskills/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in `block in halting'
     # /Users/shachiagarwalla/.rvm/gems/ruby-2.2.0@zapskills/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in`call'
     # /Users/shachiagarwalla/.rvm/gems/ruby-2.2.0@zapskills/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in `block in halting'
     # /Users/shachiagarwalla/.rvm/gems/ruby-2.2.0@zapskills/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:92:in`call'
     # /Users/shachiagarwalla/.rvm/gems/ruby-2.2.0@zapskills/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:92:in `_run_callbacks'
     # /Users/shachiagarwalla/.rvm/gems/ruby-2.2.0@zapskills/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:734:in`_run_process_action_callbacks'
     # /Users/shachiagarwalla/.rvm/gems/ruby-2.2.0@zapskills/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:81:in `run_callbacks'
     # /Users/shachiagarwalla/.rvm/gems/ruby-2.2.0@zapskills/gems/actionpack-4.2.0/lib/abstract_controller/callbacks.rb:19:in`process_action'
     # /Users/shachiagarwalla/.rvm/gems/ruby-2.2.0@zapskills/gems/actionpack-4.2.0/lib/action_controller/metal/rescue.rb:29:in `process_action'
     # /Users/shachiagarwalla/.rvm/gems/ruby-2.2.0@zapskills/gems/actionpack-4.2.0/lib/action_controller/metal/instrumentation.rb:31:in`block in process_action'
     # /Users/shachiagarwalla/.rvm/gems/ruby-2.2.0@zapskills/gems/activesupport-4.2.0/lib/active_support/notifications.rb:164:in `block in instrument'
     # /Users/shachiagarwalla/.rvm/gems/ruby-2.2.0@zapskills/gems/activesupport-4.2.0/lib/active_support/notifications/instrumenter.rb:20:in`instrument'
     # /Users/shachiagarwalla/.rvm/gems/ruby-2.2.0@zapskills/gems/activesupport-4.2.0/lib/active_support/notifications.rb:164:in `instrument'
     # /Users/shachiagarwalla/.rvm/gems/ruby-2.2.0@zapskills/gems/actionpack-4.2.0/lib/action_controller/metal/instrumentation.rb:30:in`process_action'
     # /Users/shachiagarwalla/.rvm/gems/ruby-2.2.0@zapskills/gems/actionpack-4.2.0/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
     # /Users/shachiagarwalla/.rvm/gems/ruby-2.2.0@zapskills/gems/activerecord-4.2.0/lib/active_record/railties/controller_runtime.rb:18:in`process_action'
     # /Users/shachiagarwalla/.rvm/gems/ruby-2.2.0@zapskills/gems/actionpack-4.2.0/lib/abstract_controller/base.rb:137:in `process'
     # /Users/shachiagarwalla/.rvm/gems/ruby-2.2.0@zapskills/gems/actionview-4.2.0/lib/action_view/rendering.rb:30:in`process'
     # /Users/shachiagarwalla/.rvm/gems/ruby-2.2.0@zapskills/gems/actionpack-4.2.0/lib/action_controller/test_case.rb:629:in `process'
     # /Users/shachiagarwalla/.rvm/gems/ruby-2.2.0@zapskills/gems/actionpack-4.2.0/lib/action_controller/test_case.rb:65:in`process'
     # /Users/shachiagarwalla/.rvm/gems/ruby-2.2.0@zapskills/gems/devise-3.4.1/lib/devise/test_helpers.rb:19:in `block in process'
     # /Users/shachiagarwalla/.rvm/gems/ruby-2.2.0@zapskills/gems/devise-3.4.1/lib/devise/test_helpers.rb:72:in`catch'
     # /Users/shachiagarwalla/.rvm/gems/ruby-2.2.0@zapskills/gems/devise-3.4.1/lib/devise/test_helpers.rb:72:in `_catch_warden'
     # /Users/shachiagarwalla/.rvm/gems/ruby-2.2.0@zapskills/gems/devise-3.4.1/lib/devise/test_helpers.rb:19:in`process'
     # /Users/shachiagarwalla/.rvm/gems/ruby-2.2.0@zapskills/gems/actionpack-4.2.0/lib/action_controller/test_case.rb:505:in `get'
     # ./spec/controllers/skills_controller_spec.rb:10:in`block (3 levels) in <top (required)>'

**Comment by anthonytokosky** [comment]
The entire skills controller and all it's tests have been removed completely, because they are unneeded.
