### ISSUE TITLE
Search: Around me does not function properly

### ISSUE THREAD

**Issue by shachiagarwalla** [anthonyto/Zapskills#29]
Checking around me and then searching gives weird results (those users are also displayed who do not have the skill)

Steps to reproduce:
1. Check around me
2. Choose Italian skill
3. Enter Radius 10

**Comment by Nordeast** [comment]
It also produces the same results regardless of what skill you are using to search.

**Comment by anthonytokosky** [comment]
Resolved in be5303efdb0a4dddf787435cac9d15abf4996dcc
