### ISSUE TITLE
Multiple instances of the same skill

### ISSUE THREAD

**Issue by shachiagarwalla** [anthonyto/Zapskills#3]
I was able to add multiple instances of the same skill. Because of this I had three different skill entries for the same skill of Piano. This also resulted in showing 3 search results with the same tutor as the result. 

Profile:
....
Skills 
Piano
Description: xyz
Level: 4

Piano
Description: asdf
Level: 4

Piano
Description: 
Level: 
....

Search Result:
First name: shachi
First name: shachi
First name: shachi

**Comment by anthonytokosky** [comment]
Fixed. @shachiagarwalla please test and close this issue if done

**Comment by shachiagarwalla** [comment]
Tested, works great
