### ISSUE TITLE
Footer pages do not have sign up link

### ISSUE THREAD

**Issue by shachiagarwalla** [anthonyto/Zapskills#39]
Footer pages: About, Help, How to, Contact us, Terms and Conditions do not have the Sign up link. This is not an issue as such, it is a decision to make whether we want then there or not.

**Comment by anthonytokosky** [comment]
Yeah we need to make a decision about what exactly we want on those pages. There's like nothing there right now lol

**Comment by Nordeast** [comment]
Using the Header I gave you it removes the help and about pages. Contact page will contain our names and an email. I have all the text for the terms and condition page already written. The how to page will contain the user manual that we need to write and submit

**Comment by anthonytokosky** [comment]
Cool. So should we put a sign up link on those pages? From a UX standpoint I dunno if it's good that users have to navigate back to the homepage to sign up

**Comment by Nordeast** [comment]
yes add the sign up to the navbar if the user is not signed in already on all pages.
