### ISSUE TITLE
Date fields acting up

### ISSUE THREAD

**Issue by Nordeast** [anthonyto/Zapskills#40]
![capture](https://cloud.githubusercontent.com/assets/8978368/7383569/610902e6-ede7-11e4-956b-329b8eb016a6.PNG)
![capture2](https://cloud.githubusercontent.com/assets/8978368/7383570/6113e8e6-ede7-11e4-8901-a8ab5c064a53.PNG)

site fails on bad date input

**Comment by anthonytokosky** [comment]
Yeah we need front end validation on this. We'll get it taken care of before the final presentation. Although honestly, little things like this aren't a huge deal. No one is gunna know/care
