### ISSUE TITLE
warning: duplicated key at line xx ignored: :class

### ISSUE THREAD

**Issue by shachiagarwalla** [anthonyto/Zapskills#41]
Zapskills/app/views/welcome/main.html.erb:51: warning: duplicated key at line 51 ignored: :class
Zapskills/app/views/welcome/main.html.erb:51: warning: duplicated key at line 56 ignored: :class
Zapskills/app/views/welcome/main.html.erb:51: warning: duplicated key at line 61 ignored: :class

These warnings come up every time a test is run.

**Comment by anthonytokosky** [comment]
resolved in f5b5efe029b0e981a36455ddf1a23753ae4d5345
