### ISSUE TITLE
Star ratings are unaligned when half star is included

### ISSUE THREAD

**Issue by anthonytokosky** [anthonyto/Zapskills#44]
![screen shot 2015-04-30 at 9 37 55 am](https://cloud.githubusercontent.com/assets/1906585/7415201/cd4cf67a-ef1c-11e4-8dcb-d3deb5714388.png)
@Nordeast Hey can you take a look at this? Basically, we want all the star images (0.5, 1, 2, 3, 4, 5 stars) to all be centered with each other, aligned and have the same dimensions. The half star is especially important. 

If its easier, just include two images (one full star and one half star) instead of all the different star counts. Whatever is easier for you.

**Comment by Nordeast** [comment]
There is a one star and a half star already included in the images. If those do not work let me know. 
They should be the same dimensions because I made them from the same file.

**Comment by anthonytokosky** [comment]
![screen shot 2015-04-30 at 10 03 07 am](https://cloud.githubusercontent.com/assets/1906585/7415683/244d1934-ef20-11e4-82d3-33ce90982a5f.png)

Looks like they are still unaligned a bit. Just realign the half star with that one star image and we should be good

**Comment by Nordeast** [comment]
sent via facebook

**Comment by anthonytokosky** [comment]
Looks good. Resolved in 4cc4fd681708b2e230534d0ba6e0a54a24f65c40
