### ISSUE TITLE
Remove footer and place as drop down in Navbar

### ISSUE THREAD

**Issue by Nordeast** [anthonyto/Zapskills#46]
Footer is too much of a pain.

**Comment by anthonytokosky** [comment]
Do we actually want to do this?

**Comment by Nordeast** [comment]
I think a drop down that says "more" might be nice. I think it would just alleviate the stupid footer issues

**Comment by anthonytokosky** [comment]
I'll look into it. We are already having header issues with responsiveness and I don't want the header to get too cluttered when in mobile ya feel

**Comment by Nordeast** [comment]
yes I feel ya. I will see if I can write something that works also. Also I think we should scrap about and help pages because we have no content to put in them.

**Comment by anthonytokosky** [comment]
Resolved in 9fbe77162f946b0549ed76fd664eb327cb39f2c1
