### ISSUE TITLE
Can a user add two different reviews for the same skill of a particular user?

### ISSUE THREAD

**Issue by shachiagarwalla** [anthonyto/Zapskills#50]
Should this be allowed? It is allowed as of now.

**Comment by Nordeast** [comment]
yes. if the user had multiple sessions with the other user then multiple reviews should be allowed. we do not track meetings so we cannot tell how many sessions they had so we should leave it. if some one asks "about reviews" and "if  then user can just leave many bad reviews of a user." Then we tell them that a user can submit a complaint to us and have us review them and see on a case by case basis if the reviews are reasonable.
