### ISSUE TITLE
The level of skill displayed on Profile starts from 0

### ISSUE THREAD

**Issue by shachiagarwalla** [anthonyto/Zapskills#52]
![screen shot 2015-05-02 at 12 07 02 pm](https://cloud.githubusercontent.com/assets/8856302/7441947/bfa0033e-f0c3-11e4-9306-99aa729f2300.png)

**Comment by shachiagarwalla** [comment]
Dup of 37

**Comment by Nordeast** [comment]
Stars not aligned on mobile

**Comment by Nordeast** [comment]
![screenshot_2015-05-03-21-16-48](https://cloud.githubusercontent.com/assets/8978368/7448241/10594634-f1da-11e4-83a9-148bcf651124.png)

**Comment by anthonytokosky** [comment]
What is the expected behavior? At this point, I think that'll have to do. Thoughts?

**Comment by Nordeast** [comment]
Yea I guess screw it.
