### ISSUE TITLE
Signup just after Signout gives the message "signed out successfully"

### ISSUE THREAD

**Issue by shachiagarwalla** [anthonyto/Zapskills#56]
![screen shot 2015-05-04 at 1 58 40 pm](https://cloud.githubusercontent.com/assets/8856302/7460012/ada0f802-f265-11e4-81a9-9c0836959b38.png)
1. Sign in
2. Click on Sign out
3. Click on Get started Today
The message would be displayed. "Signed out successfully"
Same thing happens if i go to login page again in step 3

**Comment by anthonytokosky** [comment]
Resolved
