### ISSUE TITLE
Multiple Header buttons

### ISSUE THREAD

**Issue by shachiagarwalla** [anthonyto/Zapskills#57]
If you do an inspect of the page, and see all code, you can see multiple buttons for header buttons. Due to this tests fail because now it is not able to recognize which button to click among the two
![screen shot 2015-05-04 at 4 02 37 pm](https://cloud.githubusercontent.com/assets/8856302/7462426/ff2324dc-f276-11e4-9803-78395e3fa0e6.png)

**Comment by anthonytokosky** [comment]
Lol this was our really hacky way to fix the fixed header resize issue. I'll just change the names of the header buttons, that should be fine right?

**Comment by shachiagarwalla** [comment]
Yes. That will work. Thanks!!

**Comment by anthonytokosky** [comment]
Resolved. just took the header out completely
