### ISSUE TITLE
Terms and conditions page not scrollable

### ISSUE THREAD

**Issue by Nordeast** [anthonyto/Zapskills#59]
To produce start on landing page and click the link to terms and conditions. The terms and conditions page is not scroll able unless you then refresh the page. Very odd error. I have only tested it on Firefox.

**Comment by Nordeast** [comment]
lol no buttons work in opera

**Comment by Nordeast** [comment]
same scrolling problem happens in chrome

**Comment by shachiagarwalla** [comment]
This problem happens for the Profile page as well. But goes after refresh

**Comment by anthonytokosky** [comment]
resolved
