### ISSUE TITLE
Back link in the Editing User Page is a little misleading

### ISSUE THREAD

**Issue by shachiagarwalla** [anthonyto/Zapskills#6]
On clicking the back button, the app takes me to the list of the users , which looks kind of misleading because I expected it to go to my profile again. 
If what I think is true, then do we need two buttons (show and back)?  because show button takes me back to the profile of the current user itself

**Comment by anthonytokosky** [comment]
Yeah I'm gunna take that button out completely, because the browser obviously already has a back button.

**Comment by anthonytokosky** [comment]
Removed the button completely. Fixed.
