### ISSUE TITLE
Edit Profile and Add skills : Date starts from 2010 only

### ISSUE THREAD

**Issue by shachiagarwalla** [anthonyto/Zapskills#7]
The year field of Date of Birth in Edit Profile page starts from 2010 and extends unto 2020.
Same is happening in the Date field of Add skills page

**Comment by anthonytokosky** [comment]
Oh shit this is a bad one hahah. Thats an HTML5 error. Lets look into this with the front end guys

**Comment by anthonytokosky** [comment]
Works in chrome, but not firefox and safari. Gotta find a better way to do this
