### ISSUE TITLE
Range error in creating new skill

### ISSUE THREAD

**Issue by Nordeast** [anthonyto/Zapskills#8]
When you are creating a new skill, when a number too large is put into the level box the action controller throws a rangeerror excpetion

**Comment by anthonytokosky** [comment]
Thanks for bringing this up. This is a UX issue, we really should be adding a dropbox to that instead of allowing custom user input. We'll bring this up with the front end guys

**Comment by anthonytokosky** [comment]
Fixed in commit 0852a86751039fcedee7760fd074a05061cce614
